//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InteractionSearch.NCBIBlastServiceAsync {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://soap.jdispatcher.ebi.ac.uk", ConfigurationName="NCBIBlastServiceAsync.JDispatcherService")]
    public interface JDispatcherService {
        
        // CODEGEN: Parameter 'jobId' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:Run", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="jobId")]
        InteractionSearch.NCBIBlastServiceAsync.runResponse run(InteractionSearch.NCBIBlastServiceAsync.runRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:Run", ReplyAction="*")]
        System.IAsyncResult Beginrun(InteractionSearch.NCBIBlastServiceAsync.runRequest request, System.AsyncCallback callback, object asyncState);
        
        InteractionSearch.NCBIBlastServiceAsync.runResponse Endrun(System.IAsyncResult result);
        
        // CODEGEN: Parameter 'status' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:GetStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        InteractionSearch.NCBIBlastServiceAsync.getStatusResponse getStatus(InteractionSearch.NCBIBlastServiceAsync.getStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:GetStatus", ReplyAction="*")]
        System.IAsyncResult BegingetStatus(InteractionSearch.NCBIBlastServiceAsync.getStatusRequest request, System.AsyncCallback callback, object asyncState);
        
        InteractionSearch.NCBIBlastServiceAsync.getStatusResponse EndgetStatus(System.IAsyncResult result);
        
        // CODEGEN: Parameter 'resultTypes' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:GetResultTypes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resultTypes")]
        InteractionSearch.NCBIBlastServiceAsync.getResultTypesResponse getResultTypes(InteractionSearch.NCBIBlastServiceAsync.getResultTypesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:GetResultTypes", ReplyAction="*")]
        System.IAsyncResult BegingetResultTypes(InteractionSearch.NCBIBlastServiceAsync.getResultTypesRequest request, System.AsyncCallback callback, object asyncState);
        
        InteractionSearch.NCBIBlastServiceAsync.getResultTypesResponse EndgetResultTypes(System.IAsyncResult result);
        
        // CODEGEN: Parameter 'output' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:GetResult", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="output")]
        InteractionSearch.NCBIBlastServiceAsync.getResultResponse getResult(InteractionSearch.NCBIBlastServiceAsync.getResultRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:GetResult", ReplyAction="*")]
        System.IAsyncResult BegingetResult(InteractionSearch.NCBIBlastServiceAsync.getResultRequest request, System.AsyncCallback callback, object asyncState);
        
        InteractionSearch.NCBIBlastServiceAsync.getResultResponse EndgetResult(System.IAsyncResult result);
        
        // CODEGEN: Parameter 'parameters' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:GetParameters", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="parameters")]
        InteractionSearch.NCBIBlastServiceAsync.getParametersResponse getParameters(InteractionSearch.NCBIBlastServiceAsync.getParametersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:GetParameters", ReplyAction="*")]
        System.IAsyncResult BegingetParameters(InteractionSearch.NCBIBlastServiceAsync.getParametersRequest request, System.AsyncCallback callback, object asyncState);
        
        InteractionSearch.NCBIBlastServiceAsync.getParametersResponse EndgetParameters(System.IAsyncResult result);
        
        // CODEGEN: Parameter 'parameterDetails' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:GetParameterDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="parameterDetails")]
        InteractionSearch.NCBIBlastServiceAsync.getParameterDetailsResponse getParameterDetails(InteractionSearch.NCBIBlastServiceAsync.getParameterDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:GetParameterDetails", ReplyAction="*")]
        System.IAsyncResult BegingetParameterDetails(InteractionSearch.NCBIBlastServiceAsync.getParameterDetailsRequest request, System.AsyncCallback callback, object asyncState);
        
        InteractionSearch.NCBIBlastServiceAsync.getParameterDetailsResponse EndgetParameterDetails(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.jdispatcher.ebi.ac.uk")]
    public partial class InputParameters : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string programField;
        
        private string matrixField;
        
        private System.Nullable<int> alignmentsField;
        
        private bool alignmentsFieldSpecified;
        
        private System.Nullable<int> scoresField;
        
        private bool scoresFieldSpecified;
        
        private string expField;
        
        private System.Nullable<int> dropoffField;
        
        private bool dropoffFieldSpecified;
        
        private string match_scoresField;
        
        private System.Nullable<int> gapopenField;
        
        private bool gapopenFieldSpecified;
        
        private System.Nullable<int> gapextField;
        
        private bool gapextFieldSpecified;
        
        private string filterField;
        
        private string seqrangeField;
        
        private System.Nullable<bool> gapalignField;
        
        private bool gapalignFieldSpecified;
        
        private System.Nullable<int> alignField;
        
        private bool alignFieldSpecified;
        
        private string stypeField;
        
        private string sequenceField;
        
        private string[] databaseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string program {
            get {
                return this.programField;
            }
            set {
                this.programField = value;
                this.RaisePropertyChanged("program");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string matrix {
            get {
                return this.matrixField;
            }
            set {
                this.matrixField = value;
                this.RaisePropertyChanged("matrix");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public System.Nullable<int> alignments {
            get {
                return this.alignmentsField;
            }
            set {
                this.alignmentsField = value;
                this.RaisePropertyChanged("alignments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool alignmentsSpecified {
            get {
                return this.alignmentsFieldSpecified;
            }
            set {
                this.alignmentsFieldSpecified = value;
                this.RaisePropertyChanged("alignmentsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public System.Nullable<int> scores {
            get {
                return this.scoresField;
            }
            set {
                this.scoresField = value;
                this.RaisePropertyChanged("scores");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool scoresSpecified {
            get {
                return this.scoresFieldSpecified;
            }
            set {
                this.scoresFieldSpecified = value;
                this.RaisePropertyChanged("scoresSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string exp {
            get {
                return this.expField;
            }
            set {
                this.expField = value;
                this.RaisePropertyChanged("exp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public System.Nullable<int> dropoff {
            get {
                return this.dropoffField;
            }
            set {
                this.dropoffField = value;
                this.RaisePropertyChanged("dropoff");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dropoffSpecified {
            get {
                return this.dropoffFieldSpecified;
            }
            set {
                this.dropoffFieldSpecified = value;
                this.RaisePropertyChanged("dropoffSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string match_scores {
            get {
                return this.match_scoresField;
            }
            set {
                this.match_scoresField = value;
                this.RaisePropertyChanged("match_scores");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public System.Nullable<int> gapopen {
            get {
                return this.gapopenField;
            }
            set {
                this.gapopenField = value;
                this.RaisePropertyChanged("gapopen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gapopenSpecified {
            get {
                return this.gapopenFieldSpecified;
            }
            set {
                this.gapopenFieldSpecified = value;
                this.RaisePropertyChanged("gapopenSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public System.Nullable<int> gapext {
            get {
                return this.gapextField;
            }
            set {
                this.gapextField = value;
                this.RaisePropertyChanged("gapext");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gapextSpecified {
            get {
                return this.gapextFieldSpecified;
            }
            set {
                this.gapextFieldSpecified = value;
                this.RaisePropertyChanged("gapextSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public string filter {
            get {
                return this.filterField;
            }
            set {
                this.filterField = value;
                this.RaisePropertyChanged("filter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public string seqrange {
            get {
                return this.seqrangeField;
            }
            set {
                this.seqrangeField = value;
                this.RaisePropertyChanged("seqrange");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        public System.Nullable<bool> gapalign {
            get {
                return this.gapalignField;
            }
            set {
                this.gapalignField = value;
                this.RaisePropertyChanged("gapalign");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gapalignSpecified {
            get {
                return this.gapalignFieldSpecified;
            }
            set {
                this.gapalignFieldSpecified = value;
                this.RaisePropertyChanged("gapalignSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=12)]
        public System.Nullable<int> align {
            get {
                return this.alignField;
            }
            set {
                this.alignField = value;
                this.RaisePropertyChanged("align");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool alignSpecified {
            get {
                return this.alignFieldSpecified;
            }
            set {
                this.alignFieldSpecified = value;
                this.RaisePropertyChanged("alignSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string stype {
            get {
                return this.stypeField;
            }
            set {
                this.stypeField = value;
                this.RaisePropertyChanged("stype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=14)]
        public string sequence {
            get {
                return this.sequenceField;
            }
            set {
                this.sequenceField = value;
                this.RaisePropertyChanged("sequence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] database {
            get {
                return this.databaseField;
            }
            set {
                this.databaseField = value;
                this.RaisePropertyChanged("database");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.jdispatcher.ebi.ac.uk")]
    public partial class wsProperty : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.jdispatcher.ebi.ac.uk")]
    public partial class wsParameterValue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string labelField;
        
        private string valueField;
        
        private bool defaultValueField;
        
        private wsProperty[] propertiesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
                this.RaisePropertyChanged("label");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool defaultValue {
            get {
                return this.defaultValueField;
            }
            set {
                this.defaultValueField = value;
                this.RaisePropertyChanged("defaultValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public wsProperty[] properties {
            get {
                return this.propertiesField;
            }
            set {
                this.propertiesField = value;
                this.RaisePropertyChanged("properties");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.jdispatcher.ebi.ac.uk")]
    public partial class wsParameterDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string descriptionField;
        
        private string typeField;
        
        private wsParameterValue[] valuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("value", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public wsParameterValue[] values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
                this.RaisePropertyChanged("values");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.jdispatcher.ebi.ac.uk")]
    public partial class wsRawOutputParameter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.jdispatcher.ebi.ac.uk")]
    public partial class wsResultType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        private string fileSuffixField;
        
        private string identifierField;
        
        private string labelField;
        
        private string mediaTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fileSuffix {
            get {
                return this.fileSuffixField;
            }
            set {
                this.fileSuffixField = value;
                this.RaisePropertyChanged("fileSuffix");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
                this.RaisePropertyChanged("identifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
                this.RaisePropertyChanged("label");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string mediaType {
            get {
                return this.mediaTypeField;
            }
            set {
                this.mediaTypeField = value;
                this.RaisePropertyChanged("mediaType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="run", WrapperNamespace="http://soap.jdispatcher.ebi.ac.uk", IsWrapped=true)]
    public partial class runRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.jdispatcher.ebi.ac.uk", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.jdispatcher.ebi.ac.uk", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string title;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.jdispatcher.ebi.ac.uk", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InteractionSearch.NCBIBlastServiceAsync.InputParameters parameters;
        
        public runRequest() {
        }
        
        public runRequest(string email, string title, InteractionSearch.NCBIBlastServiceAsync.InputParameters parameters) {
            this.email = email;
            this.title = title;
            this.parameters = parameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="runResponse", WrapperNamespace="http://soap.jdispatcher.ebi.ac.uk", IsWrapped=true)]
    public partial class runResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.jdispatcher.ebi.ac.uk", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string jobId;
        
        public runResponse() {
        }
        
        public runResponse(string jobId) {
            this.jobId = jobId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStatus", WrapperNamespace="http://soap.jdispatcher.ebi.ac.uk", IsWrapped=true)]
    public partial class getStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.jdispatcher.ebi.ac.uk", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string jobId;
        
        public getStatusRequest() {
        }
        
        public getStatusRequest(string jobId) {
            this.jobId = jobId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStatusResponse", WrapperNamespace="http://soap.jdispatcher.ebi.ac.uk", IsWrapped=true)]
    public partial class getStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.jdispatcher.ebi.ac.uk", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string status;
        
        public getStatusResponse() {
        }
        
        public getStatusResponse(string status) {
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getResultTypes", WrapperNamespace="http://soap.jdispatcher.ebi.ac.uk", IsWrapped=true)]
    public partial class getResultTypesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.jdispatcher.ebi.ac.uk", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string jobId;
        
        public getResultTypesRequest() {
        }
        
        public getResultTypesRequest(string jobId) {
            this.jobId = jobId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getResultTypesResponse", WrapperNamespace="http://soap.jdispatcher.ebi.ac.uk", IsWrapped=true)]
    public partial class getResultTypesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.jdispatcher.ebi.ac.uk", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("type", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public wsResultType[] resultTypes;
        
        public getResultTypesResponse() {
        }
        
        public getResultTypesResponse(wsResultType[] resultTypes) {
            this.resultTypes = resultTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getResult", WrapperNamespace="http://soap.jdispatcher.ebi.ac.uk", IsWrapped=true)]
    public partial class getResultRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.jdispatcher.ebi.ac.uk", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string jobId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.jdispatcher.ebi.ac.uk", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.jdispatcher.ebi.ac.uk", Order=2)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("parameter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public wsRawOutputParameter[] parameters;
        
        public getResultRequest() {
        }
        
        public getResultRequest(string jobId, string type, wsRawOutputParameter[] parameters) {
            this.jobId = jobId;
            this.type = type;
            this.parameters = parameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getResultResponse", WrapperNamespace="http://soap.jdispatcher.ebi.ac.uk", IsWrapped=true)]
    public partial class getResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.jdispatcher.ebi.ac.uk", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] output;
        
        public getResultResponse() {
        }
        
        public getResultResponse(byte[] output) {
            this.output = output;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getParameters", WrapperNamespace="http://soap.jdispatcher.ebi.ac.uk", IsWrapped=true)]
    public partial class getParametersRequest {
        
        public getParametersRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getParametersResponse", WrapperNamespace="http://soap.jdispatcher.ebi.ac.uk", IsWrapped=true)]
    public partial class getParametersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.jdispatcher.ebi.ac.uk", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] parameters;
        
        public getParametersResponse() {
        }
        
        public getParametersResponse(string[] parameters) {
            this.parameters = parameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getParameterDetails", WrapperNamespace="http://soap.jdispatcher.ebi.ac.uk", IsWrapped=true)]
    public partial class getParameterDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.jdispatcher.ebi.ac.uk", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string parameterId;
        
        public getParameterDetailsRequest() {
        }
        
        public getParameterDetailsRequest(string parameterId) {
            this.parameterId = parameterId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getParameterDetailsResponse", WrapperNamespace="http://soap.jdispatcher.ebi.ac.uk", IsWrapped=true)]
    public partial class getParameterDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.jdispatcher.ebi.ac.uk", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InteractionSearch.NCBIBlastServiceAsync.wsParameterDetails parameterDetails;
        
        public getParameterDetailsResponse() {
        }
        
        public getParameterDetailsResponse(InteractionSearch.NCBIBlastServiceAsync.wsParameterDetails parameterDetails) {
            this.parameterDetails = parameterDetails;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface JDispatcherServiceChannel : InteractionSearch.NCBIBlastServiceAsync.JDispatcherService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class runCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public runCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class getStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class getResultTypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getResultTypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public wsResultType[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((wsResultType[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class getResultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getResultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public byte[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class getParametersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getParametersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class getParameterDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getParameterDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public InteractionSearch.NCBIBlastServiceAsync.wsParameterDetails Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((InteractionSearch.NCBIBlastServiceAsync.wsParameterDetails)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class JDispatcherServiceClient : System.ServiceModel.ClientBase<InteractionSearch.NCBIBlastServiceAsync.JDispatcherService>, InteractionSearch.NCBIBlastServiceAsync.JDispatcherService {
        
        private BeginOperationDelegate onBeginrunDelegate;
        
        private EndOperationDelegate onEndrunDelegate;
        
        private System.Threading.SendOrPostCallback onrunCompletedDelegate;
        
        private BeginOperationDelegate onBegingetStatusDelegate;
        
        private EndOperationDelegate onEndgetStatusDelegate;
        
        private System.Threading.SendOrPostCallback ongetStatusCompletedDelegate;
        
        private BeginOperationDelegate onBegingetResultTypesDelegate;
        
        private EndOperationDelegate onEndgetResultTypesDelegate;
        
        private System.Threading.SendOrPostCallback ongetResultTypesCompletedDelegate;
        
        private BeginOperationDelegate onBegingetResultDelegate;
        
        private EndOperationDelegate onEndgetResultDelegate;
        
        private System.Threading.SendOrPostCallback ongetResultCompletedDelegate;
        
        private BeginOperationDelegate onBegingetParametersDelegate;
        
        private EndOperationDelegate onEndgetParametersDelegate;
        
        private System.Threading.SendOrPostCallback ongetParametersCompletedDelegate;
        
        private BeginOperationDelegate onBegingetParameterDetailsDelegate;
        
        private EndOperationDelegate onEndgetParameterDetailsDelegate;
        
        private System.Threading.SendOrPostCallback ongetParameterDetailsCompletedDelegate;
        
        public JDispatcherServiceClient() {
        }
        
        public JDispatcherServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JDispatcherServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JDispatcherServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JDispatcherServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<runCompletedEventArgs> runCompleted;
        
        public event System.EventHandler<getStatusCompletedEventArgs> getStatusCompleted;
        
        public event System.EventHandler<getResultTypesCompletedEventArgs> getResultTypesCompleted;
        
        public event System.EventHandler<getResultCompletedEventArgs> getResultCompleted;
        
        public event System.EventHandler<getParametersCompletedEventArgs> getParametersCompleted;
        
        public event System.EventHandler<getParameterDetailsCompletedEventArgs> getParameterDetailsCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InteractionSearch.NCBIBlastServiceAsync.runResponse InteractionSearch.NCBIBlastServiceAsync.JDispatcherService.run(InteractionSearch.NCBIBlastServiceAsync.runRequest request) {
            return base.Channel.run(request);
        }
        
        public string run(string email, string title, InteractionSearch.NCBIBlastServiceAsync.InputParameters parameters) {
            InteractionSearch.NCBIBlastServiceAsync.runRequest inValue = new InteractionSearch.NCBIBlastServiceAsync.runRequest();
            inValue.email = email;
            inValue.title = title;
            inValue.parameters = parameters;
            InteractionSearch.NCBIBlastServiceAsync.runResponse retVal = ((InteractionSearch.NCBIBlastServiceAsync.JDispatcherService)(this)).run(inValue);
            return retVal.jobId;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult InteractionSearch.NCBIBlastServiceAsync.JDispatcherService.Beginrun(InteractionSearch.NCBIBlastServiceAsync.runRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginrun(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult Beginrun(string email, string title, InteractionSearch.NCBIBlastServiceAsync.InputParameters parameters, System.AsyncCallback callback, object asyncState) {
            InteractionSearch.NCBIBlastServiceAsync.runRequest inValue = new InteractionSearch.NCBIBlastServiceAsync.runRequest();
            inValue.email = email;
            inValue.title = title;
            inValue.parameters = parameters;
            return ((InteractionSearch.NCBIBlastServiceAsync.JDispatcherService)(this)).Beginrun(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InteractionSearch.NCBIBlastServiceAsync.runResponse InteractionSearch.NCBIBlastServiceAsync.JDispatcherService.Endrun(System.IAsyncResult result) {
            return base.Channel.Endrun(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string Endrun(System.IAsyncResult result) {
            InteractionSearch.NCBIBlastServiceAsync.runResponse retVal = ((InteractionSearch.NCBIBlastServiceAsync.JDispatcherService)(this)).Endrun(result);
            return retVal.jobId;
        }
        
        private System.IAsyncResult OnBeginrun(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string email = ((string)(inValues[0]));
            string title = ((string)(inValues[1]));
            InteractionSearch.NCBIBlastServiceAsync.InputParameters parameters = ((InteractionSearch.NCBIBlastServiceAsync.InputParameters)(inValues[2]));
            return this.Beginrun(email, title, parameters, callback, asyncState);
        }
        
        private object[] OnEndrun(System.IAsyncResult result) {
            string retVal = this.Endrun(result);
            return new object[] {
                    retVal};
        }
        
        private void OnrunCompleted(object state) {
            if ((this.runCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.runCompleted(this, new runCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void runAsync(string email, string title, InteractionSearch.NCBIBlastServiceAsync.InputParameters parameters) {
            this.runAsync(email, title, parameters, null);
        }
        
        public void runAsync(string email, string title, InteractionSearch.NCBIBlastServiceAsync.InputParameters parameters, object userState) {
            if ((this.onBeginrunDelegate == null)) {
                this.onBeginrunDelegate = new BeginOperationDelegate(this.OnBeginrun);
            }
            if ((this.onEndrunDelegate == null)) {
                this.onEndrunDelegate = new EndOperationDelegate(this.OnEndrun);
            }
            if ((this.onrunCompletedDelegate == null)) {
                this.onrunCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnrunCompleted);
            }
            base.InvokeAsync(this.onBeginrunDelegate, new object[] {
                        email,
                        title,
                        parameters}, this.onEndrunDelegate, this.onrunCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InteractionSearch.NCBIBlastServiceAsync.getStatusResponse InteractionSearch.NCBIBlastServiceAsync.JDispatcherService.getStatus(InteractionSearch.NCBIBlastServiceAsync.getStatusRequest request) {
            return base.Channel.getStatus(request);
        }
        
        public string getStatus(string jobId) {
            InteractionSearch.NCBIBlastServiceAsync.getStatusRequest inValue = new InteractionSearch.NCBIBlastServiceAsync.getStatusRequest();
            inValue.jobId = jobId;
            InteractionSearch.NCBIBlastServiceAsync.getStatusResponse retVal = ((InteractionSearch.NCBIBlastServiceAsync.JDispatcherService)(this)).getStatus(inValue);
            return retVal.status;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult InteractionSearch.NCBIBlastServiceAsync.JDispatcherService.BegingetStatus(InteractionSearch.NCBIBlastServiceAsync.getStatusRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetStatus(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegingetStatus(string jobId, System.AsyncCallback callback, object asyncState) {
            InteractionSearch.NCBIBlastServiceAsync.getStatusRequest inValue = new InteractionSearch.NCBIBlastServiceAsync.getStatusRequest();
            inValue.jobId = jobId;
            return ((InteractionSearch.NCBIBlastServiceAsync.JDispatcherService)(this)).BegingetStatus(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InteractionSearch.NCBIBlastServiceAsync.getStatusResponse InteractionSearch.NCBIBlastServiceAsync.JDispatcherService.EndgetStatus(System.IAsyncResult result) {
            return base.Channel.EndgetStatus(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndgetStatus(System.IAsyncResult result) {
            InteractionSearch.NCBIBlastServiceAsync.getStatusResponse retVal = ((InteractionSearch.NCBIBlastServiceAsync.JDispatcherService)(this)).EndgetStatus(result);
            return retVal.status;
        }
        
        private System.IAsyncResult OnBegingetStatus(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string jobId = ((string)(inValues[0]));
            return this.BegingetStatus(jobId, callback, asyncState);
        }
        
        private object[] OnEndgetStatus(System.IAsyncResult result) {
            string retVal = this.EndgetStatus(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetStatusCompleted(object state) {
            if ((this.getStatusCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getStatusCompleted(this, new getStatusCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getStatusAsync(string jobId) {
            this.getStatusAsync(jobId, null);
        }
        
        public void getStatusAsync(string jobId, object userState) {
            if ((this.onBegingetStatusDelegate == null)) {
                this.onBegingetStatusDelegate = new BeginOperationDelegate(this.OnBegingetStatus);
            }
            if ((this.onEndgetStatusDelegate == null)) {
                this.onEndgetStatusDelegate = new EndOperationDelegate(this.OnEndgetStatus);
            }
            if ((this.ongetStatusCompletedDelegate == null)) {
                this.ongetStatusCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetStatusCompleted);
            }
            base.InvokeAsync(this.onBegingetStatusDelegate, new object[] {
                        jobId}, this.onEndgetStatusDelegate, this.ongetStatusCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InteractionSearch.NCBIBlastServiceAsync.getResultTypesResponse InteractionSearch.NCBIBlastServiceAsync.JDispatcherService.getResultTypes(InteractionSearch.NCBIBlastServiceAsync.getResultTypesRequest request) {
            return base.Channel.getResultTypes(request);
        }
        
        public wsResultType[] getResultTypes(string jobId) {
            InteractionSearch.NCBIBlastServiceAsync.getResultTypesRequest inValue = new InteractionSearch.NCBIBlastServiceAsync.getResultTypesRequest();
            inValue.jobId = jobId;
            InteractionSearch.NCBIBlastServiceAsync.getResultTypesResponse retVal = ((InteractionSearch.NCBIBlastServiceAsync.JDispatcherService)(this)).getResultTypes(inValue);
            return retVal.resultTypes;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult InteractionSearch.NCBIBlastServiceAsync.JDispatcherService.BegingetResultTypes(InteractionSearch.NCBIBlastServiceAsync.getResultTypesRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetResultTypes(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegingetResultTypes(string jobId, System.AsyncCallback callback, object asyncState) {
            InteractionSearch.NCBIBlastServiceAsync.getResultTypesRequest inValue = new InteractionSearch.NCBIBlastServiceAsync.getResultTypesRequest();
            inValue.jobId = jobId;
            return ((InteractionSearch.NCBIBlastServiceAsync.JDispatcherService)(this)).BegingetResultTypes(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InteractionSearch.NCBIBlastServiceAsync.getResultTypesResponse InteractionSearch.NCBIBlastServiceAsync.JDispatcherService.EndgetResultTypes(System.IAsyncResult result) {
            return base.Channel.EndgetResultTypes(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public wsResultType[] EndgetResultTypes(System.IAsyncResult result) {
            InteractionSearch.NCBIBlastServiceAsync.getResultTypesResponse retVal = ((InteractionSearch.NCBIBlastServiceAsync.JDispatcherService)(this)).EndgetResultTypes(result);
            return retVal.resultTypes;
        }
        
        private System.IAsyncResult OnBegingetResultTypes(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string jobId = ((string)(inValues[0]));
            return this.BegingetResultTypes(jobId, callback, asyncState);
        }
        
        private object[] OnEndgetResultTypes(System.IAsyncResult result) {
            wsResultType[] retVal = this.EndgetResultTypes(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetResultTypesCompleted(object state) {
            if ((this.getResultTypesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getResultTypesCompleted(this, new getResultTypesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getResultTypesAsync(string jobId) {
            this.getResultTypesAsync(jobId, null);
        }
        
        public void getResultTypesAsync(string jobId, object userState) {
            if ((this.onBegingetResultTypesDelegate == null)) {
                this.onBegingetResultTypesDelegate = new BeginOperationDelegate(this.OnBegingetResultTypes);
            }
            if ((this.onEndgetResultTypesDelegate == null)) {
                this.onEndgetResultTypesDelegate = new EndOperationDelegate(this.OnEndgetResultTypes);
            }
            if ((this.ongetResultTypesCompletedDelegate == null)) {
                this.ongetResultTypesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetResultTypesCompleted);
            }
            base.InvokeAsync(this.onBegingetResultTypesDelegate, new object[] {
                        jobId}, this.onEndgetResultTypesDelegate, this.ongetResultTypesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InteractionSearch.NCBIBlastServiceAsync.getResultResponse InteractionSearch.NCBIBlastServiceAsync.JDispatcherService.getResult(InteractionSearch.NCBIBlastServiceAsync.getResultRequest request) {
            return base.Channel.getResult(request);
        }
        
        public byte[] getResult(string jobId, string type, wsRawOutputParameter[] parameters) {
            InteractionSearch.NCBIBlastServiceAsync.getResultRequest inValue = new InteractionSearch.NCBIBlastServiceAsync.getResultRequest();
            inValue.jobId = jobId;
            inValue.type = type;
            inValue.parameters = parameters;
            InteractionSearch.NCBIBlastServiceAsync.getResultResponse retVal = ((InteractionSearch.NCBIBlastServiceAsync.JDispatcherService)(this)).getResult(inValue);
            return retVal.output;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult InteractionSearch.NCBIBlastServiceAsync.JDispatcherService.BegingetResult(InteractionSearch.NCBIBlastServiceAsync.getResultRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetResult(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegingetResult(string jobId, string type, wsRawOutputParameter[] parameters, System.AsyncCallback callback, object asyncState) {
            InteractionSearch.NCBIBlastServiceAsync.getResultRequest inValue = new InteractionSearch.NCBIBlastServiceAsync.getResultRequest();
            inValue.jobId = jobId;
            inValue.type = type;
            inValue.parameters = parameters;
            return ((InteractionSearch.NCBIBlastServiceAsync.JDispatcherService)(this)).BegingetResult(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InteractionSearch.NCBIBlastServiceAsync.getResultResponse InteractionSearch.NCBIBlastServiceAsync.JDispatcherService.EndgetResult(System.IAsyncResult result) {
            return base.Channel.EndgetResult(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public byte[] EndgetResult(System.IAsyncResult result) {
            InteractionSearch.NCBIBlastServiceAsync.getResultResponse retVal = ((InteractionSearch.NCBIBlastServiceAsync.JDispatcherService)(this)).EndgetResult(result);
            return retVal.output;
        }
        
        private System.IAsyncResult OnBegingetResult(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string jobId = ((string)(inValues[0]));
            string type = ((string)(inValues[1]));
            wsRawOutputParameter[] parameters = ((wsRawOutputParameter[])(inValues[2]));
            return this.BegingetResult(jobId, type, parameters, callback, asyncState);
        }
        
        private object[] OnEndgetResult(System.IAsyncResult result) {
            byte[] retVal = this.EndgetResult(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetResultCompleted(object state) {
            if ((this.getResultCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getResultCompleted(this, new getResultCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getResultAsync(string jobId, string type, wsRawOutputParameter[] parameters) {
            this.getResultAsync(jobId, type, parameters, null);
        }
        
        public void getResultAsync(string jobId, string type, wsRawOutputParameter[] parameters, object userState) {
            if ((this.onBegingetResultDelegate == null)) {
                this.onBegingetResultDelegate = new BeginOperationDelegate(this.OnBegingetResult);
            }
            if ((this.onEndgetResultDelegate == null)) {
                this.onEndgetResultDelegate = new EndOperationDelegate(this.OnEndgetResult);
            }
            if ((this.ongetResultCompletedDelegate == null)) {
                this.ongetResultCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetResultCompleted);
            }
            base.InvokeAsync(this.onBegingetResultDelegate, new object[] {
                        jobId,
                        type,
                        parameters}, this.onEndgetResultDelegate, this.ongetResultCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InteractionSearch.NCBIBlastServiceAsync.getParametersResponse InteractionSearch.NCBIBlastServiceAsync.JDispatcherService.getParameters(InteractionSearch.NCBIBlastServiceAsync.getParametersRequest request) {
            return base.Channel.getParameters(request);
        }
        
        public string[] getParameters() {
            InteractionSearch.NCBIBlastServiceAsync.getParametersRequest inValue = new InteractionSearch.NCBIBlastServiceAsync.getParametersRequest();
            InteractionSearch.NCBIBlastServiceAsync.getParametersResponse retVal = ((InteractionSearch.NCBIBlastServiceAsync.JDispatcherService)(this)).getParameters(inValue);
            return retVal.parameters;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult InteractionSearch.NCBIBlastServiceAsync.JDispatcherService.BegingetParameters(InteractionSearch.NCBIBlastServiceAsync.getParametersRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetParameters(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegingetParameters(System.AsyncCallback callback, object asyncState) {
            InteractionSearch.NCBIBlastServiceAsync.getParametersRequest inValue = new InteractionSearch.NCBIBlastServiceAsync.getParametersRequest();
            return ((InteractionSearch.NCBIBlastServiceAsync.JDispatcherService)(this)).BegingetParameters(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InteractionSearch.NCBIBlastServiceAsync.getParametersResponse InteractionSearch.NCBIBlastServiceAsync.JDispatcherService.EndgetParameters(System.IAsyncResult result) {
            return base.Channel.EndgetParameters(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string[] EndgetParameters(System.IAsyncResult result) {
            InteractionSearch.NCBIBlastServiceAsync.getParametersResponse retVal = ((InteractionSearch.NCBIBlastServiceAsync.JDispatcherService)(this)).EndgetParameters(result);
            return retVal.parameters;
        }
        
        private System.IAsyncResult OnBegingetParameters(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BegingetParameters(callback, asyncState);
        }
        
        private object[] OnEndgetParameters(System.IAsyncResult result) {
            string[] retVal = this.EndgetParameters(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetParametersCompleted(object state) {
            if ((this.getParametersCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getParametersCompleted(this, new getParametersCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getParametersAsync() {
            this.getParametersAsync(null);
        }
        
        public void getParametersAsync(object userState) {
            if ((this.onBegingetParametersDelegate == null)) {
                this.onBegingetParametersDelegate = new BeginOperationDelegate(this.OnBegingetParameters);
            }
            if ((this.onEndgetParametersDelegate == null)) {
                this.onEndgetParametersDelegate = new EndOperationDelegate(this.OnEndgetParameters);
            }
            if ((this.ongetParametersCompletedDelegate == null)) {
                this.ongetParametersCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetParametersCompleted);
            }
            base.InvokeAsync(this.onBegingetParametersDelegate, null, this.onEndgetParametersDelegate, this.ongetParametersCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InteractionSearch.NCBIBlastServiceAsync.getParameterDetailsResponse InteractionSearch.NCBIBlastServiceAsync.JDispatcherService.getParameterDetails(InteractionSearch.NCBIBlastServiceAsync.getParameterDetailsRequest request) {
            return base.Channel.getParameterDetails(request);
        }
        
        public InteractionSearch.NCBIBlastServiceAsync.wsParameterDetails getParameterDetails(string parameterId) {
            InteractionSearch.NCBIBlastServiceAsync.getParameterDetailsRequest inValue = new InteractionSearch.NCBIBlastServiceAsync.getParameterDetailsRequest();
            inValue.parameterId = parameterId;
            InteractionSearch.NCBIBlastServiceAsync.getParameterDetailsResponse retVal = ((InteractionSearch.NCBIBlastServiceAsync.JDispatcherService)(this)).getParameterDetails(inValue);
            return retVal.parameterDetails;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult InteractionSearch.NCBIBlastServiceAsync.JDispatcherService.BegingetParameterDetails(InteractionSearch.NCBIBlastServiceAsync.getParameterDetailsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetParameterDetails(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegingetParameterDetails(string parameterId, System.AsyncCallback callback, object asyncState) {
            InteractionSearch.NCBIBlastServiceAsync.getParameterDetailsRequest inValue = new InteractionSearch.NCBIBlastServiceAsync.getParameterDetailsRequest();
            inValue.parameterId = parameterId;
            return ((InteractionSearch.NCBIBlastServiceAsync.JDispatcherService)(this)).BegingetParameterDetails(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InteractionSearch.NCBIBlastServiceAsync.getParameterDetailsResponse InteractionSearch.NCBIBlastServiceAsync.JDispatcherService.EndgetParameterDetails(System.IAsyncResult result) {
            return base.Channel.EndgetParameterDetails(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public InteractionSearch.NCBIBlastServiceAsync.wsParameterDetails EndgetParameterDetails(System.IAsyncResult result) {
            InteractionSearch.NCBIBlastServiceAsync.getParameterDetailsResponse retVal = ((InteractionSearch.NCBIBlastServiceAsync.JDispatcherService)(this)).EndgetParameterDetails(result);
            return retVal.parameterDetails;
        }
        
        private System.IAsyncResult OnBegingetParameterDetails(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string parameterId = ((string)(inValues[0]));
            return this.BegingetParameterDetails(parameterId, callback, asyncState);
        }
        
        private object[] OnEndgetParameterDetails(System.IAsyncResult result) {
            InteractionSearch.NCBIBlastServiceAsync.wsParameterDetails retVal = this.EndgetParameterDetails(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetParameterDetailsCompleted(object state) {
            if ((this.getParameterDetailsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getParameterDetailsCompleted(this, new getParameterDetailsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getParameterDetailsAsync(string parameterId) {
            this.getParameterDetailsAsync(parameterId, null);
        }
        
        public void getParameterDetailsAsync(string parameterId, object userState) {
            if ((this.onBegingetParameterDetailsDelegate == null)) {
                this.onBegingetParameterDetailsDelegate = new BeginOperationDelegate(this.OnBegingetParameterDetails);
            }
            if ((this.onEndgetParameterDetailsDelegate == null)) {
                this.onEndgetParameterDetailsDelegate = new EndOperationDelegate(this.OnEndgetParameterDetails);
            }
            if ((this.ongetParameterDetailsCompletedDelegate == null)) {
                this.ongetParameterDetailsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetParameterDetailsCompleted);
            }
            base.InvokeAsync(this.onBegingetParameterDetailsDelegate, new object[] {
                        parameterId}, this.onEndgetParameterDetailsDelegate, this.ongetParameterDetailsCompletedDelegate, userState);
        }
    }
}
